# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from threecities.v1 import verifier_pb2 as threecities_dot_v1_dot_verifier__pb2


class VerifierServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Say = channel.unary_unary(
                '/threecities.v1.VerifierService/Say',
                request_serializer=threecities_dot_v1_dot_verifier__pb2.SayRequest.SerializeToString,
                response_deserializer=threecities_dot_v1_dot_verifier__pb2.SayResponse.FromString,
                )


class VerifierServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Say(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerifierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Say': grpc.unary_unary_rpc_method_handler(
                    servicer.Say,
                    request_deserializer=threecities_dot_v1_dot_verifier__pb2.SayRequest.FromString,
                    response_serializer=threecities_dot_v1_dot_verifier__pb2.SayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'threecities.v1.VerifierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VerifierService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Say(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/threecities.v1.VerifierService/Say',
            threecities_dot_v1_dot_verifier__pb2.SayRequest.SerializeToString,
            threecities_dot_v1_dot_verifier__pb2.SayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
