# Generated by Django 4.2.13 on 2024-07-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eth', '0010_remove_signedmessage_safe_app_transaction_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedmessage',
            name='signature',
            field=models.TextField(),
        ),
    ]
