# Generated by Django 4.2.13 on 2024-07-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eth', '0011_alter_signedmessage_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedmessage',
            name='chain_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='is_testnet',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='receipt_url',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='token_amount',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='token_contract_address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='token_currency',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='token_decimals',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='token_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='token_ticker',
            field=models.TextField(default=None, null=True),
        ),
    ]
