# Generated by Django 4.2.11 on 2024-07-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eth', '0012_signedmessage_chain_name_signedmessage_is_testnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedmessage',
            name='verification_explanation',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='verification_failed_permanently',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
